Add scripts and templates for Packer
Otus-DevOps-2018-02/supermegarega_infra pull request #5
Opened 2018-03-22 10:35 UTC by supermegarega

# Выполнено ДЗ №

 - [x] Основное ДЗ
 - [x] Задание со *

## В процессе сделано:
 - Созданы шаблоны ubuntu16.json, immutable.json, variables.json.example.
 - Созданы образы reddit-base и reddit-full.
 - Созданы скрипты deploy-puma.sh, create-reddit-vm.sh.
 - Создан инстанс reddit-app с использованием образов reddit-base и reddit-full.
 - Создан immutable инстанс reddit-app с использованием утилиты gcloud и create-reddit-vm.sh.
 - Проверена работа приложения после запуска инстансов созданных из reddit-base и reddit-full образов.

## Как запустить проект:
 - Из каталога config-scripts запустить create-reddit-vm.sh (в результате запуска будет создан инстанс reddit-app и установлен и запущен Puma сервис).

## Как проверить работоспособность:
 - Перейти по ссылке http://reddit-app:9292 и создать пользователя.

## PR checklisk
 - [x] Выставил label с номером домашнего задания
 - [x] Выставил label с темой домашнего задания

2018-03-22 14:37 UTC, vitkhab requested changes
Выглядит классно и тесты проходят. Есть хорошее описание.

Для зачета прошу сделать обязательными поля `source_image_family` и `project_id` в файле `packer/ubuntu16.json`

2018-03-22 14:37 UTC, vitkhab commented on packer/ubuntu16.json
> +        "project_id": "infra-198011",
Согласно задания, требуется сделать так, чтобы `project_id` было нужно указывать пользователю через `-var` или `-var-file`

2018-03-22 20:14 UTC, supermegarega commented
Обновил ubuntu16.json.

2018-03-30 12:39 UTC, vitkhab approved these changes
Спасибо за сделанные изменения!

2018-03-30 13:27 UTC, merged